# Generated by Django 4.1.7 on 2023-03-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groceryservice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="need",
            field=models.BooleanField(default=True),
        ),
    ]
