# Generated by Django 4.1.7 on 2023-03-20 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groceryservice", "0002_item_need"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="groceryservice.section",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
