# Generated by Django 4.1.7 on 2023-03-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groceryservice", "0003_alter_item_section_alter_section_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="groceryservice.section"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
