# Generated by Django 4.1.7 on 2023-03-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groceryservice", "0004_alter_item_section_alter_section_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ingredients", models.ManyToManyField(to="groceryservice.item")),
            ],
        ),
    ]
